### ISSUE TITLE
ホワイトリストをやめて、WorldEdit & WorldGuard で自衛してもらうスタイルにする

### ISSUE THREAD

**Issue by zztkm** [pistachiostudio/genkai-mc-server#116]
## 概要

荒らし対策として、ホワイトリスト形式を採用していたが、統合版ユーザーを入れるようにできない（できるかもしれないがやり方がわからない）& 新しい人を呼びにくい状態なので、荒らし対策は WorldEdit と WorldGuard で行うような体制にしていく。

## ToDo

- [x] WorldEdit と WorldGuard の検証
  - [x] 最低限必要なコマンドが使える権限を LuckPerms で用意する
  - [x] 権限を検証してほしいユーザーにわたす (fukakoro さんは OP 権限をつけてなんでもできるようにする予定
- [ ] ドキュメント整備 (WorldEdit と WorldGuard のドキュメントを参考にしつつ、利用イメージしやすいようにドキュメントを Wiki などにまとめる
- [ ] リリース
  - [ ] 既存ユーザーの建物保護の確認 (これやってからホワイトリストの解除を行う
  - [ ] ホワイトリストの解除

**Comment by zztkm** [comment]
無制限に region 設定できても困るので、なんらかの制限をできるか調べる
https://worldguard.enginehub.org/en/latest/config/

**Comment by zztkm** [comment]
ドキュメントに書きたいコマンド

- `//wand`
  - wand した木の斧、`tool none`
- `region define {YOUR_REGION_NAME} {OWNERS (スペース区切りで複数選択可}`
  - wand で選択した土地を region として登録する
  - region は rg という省略が使える `rg define ...`
- `region remove {YOUR_REGION_NAME}
  - リージョン削除
- `region addmember {YOUR_REGION_NAME} {PLAYER_NAME (スペース区切りで複数選択可)}`
  - addowner も同様
- `rg flags {YOUR_REGION_NAME}`
  - リージョン内の権限を変更できる
    - 主にリージョンのメンバー以外の操作に対する許可設定です
    - 変更できる値は限られています
    - 現在できない項目で、変更したいものがあれば管理者に連絡してください

以下のコマンドは自分がオーナーである region にも実行できます
-  `rg list`
- `rg info {YOUR_REGION_NAME}`
- `rg remove ...`
- `rg addmember ...`
- `rg addowner ...`
- `rg removemember ...`
- `rg removeowner ...`
- `rg flags {YOUR_REGION_NAME}`

**Comment by zztkm** [comment]
上記コマンドを実行できる人はある程度自分たちが知ってる人（誰かの知り合いとか）だけにしようかなと考えてます。

理由は、荒らしの可能性がある人にリージョンを選択できる権限を与えるのは怖いからです。

上のコマンドがなくても普通に遊べる状態ではあるので、保護ができるのは自分たちが認知してる人だけにしようかなという感じです。

**Comment by zztkm** [comment]
結局ホワイトリストに戻したのでこの issue はクローズします。
