### ISSUE TITLE
🎉 1.20 version up !

### ISSUE THREAD

**Issue by zztkm** [pistachiostudio/genkai-mc-server#30]
## 概要

1.20 にあげるための準備をする issue

## 前提

Paper MC を利用しているので、そちらが対応するまではバージョンアップできない（がんばって作業してくれているらしい）。

## ✅ TODO

- [x] バージョンアップが必要なプラグインを確認
- [x] [minecraft-docker](https://github.com/itzg/docker-minecraft-server) で Paper 1.20 が起動するかローカル検証
- [x] バージョンアップ手順を作成
- [x] https://github.com/pistachiostudio/genkai-mc-server/issues/31

### プラグインバージョンアップ可否

- [ ] [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/): 対応作業中(未リリース
- [x] [LWC](https://www.spigotmc.org/resources/lwc-extended.69551/)
- [ ] [Dynmap](https://dev.bukkit.org/projects/dynmap/files): 対応作業中(未リリース
- [ ] [Hidden Armor](https://www.spigotmc.org/resources/hidden-armor.100374/) 不明 (ProtocolLibが対応したら勝手に動くようになるかも 🤔 
- [x] [GeyserMC](https://geysermc.org/download)
- [x] [Floodgate](https://geysermc.org/download)

## ⚙️ バージョンアップ手順

- [x] Discord と server でアプデ開始を告知 
- [x] `make down`: サーバー停止
- [x] 既存 plugin jar を削除: `rm data/plugins/*.jar` & `rm data/plugins/*.json`
- [x] merge する: https://github.com/pistachiostudio/genkai-mc-server/pull/34
- [x] `git pull`
- [x] `make up` サーバー起動
- [ ] 検証
  - [x] LWC
  - [ ] Geyser & Floodgate
  - [ ] Hidden Armor

## Links

- https://www.minecraft.net/ja-jp/updates/trails-and-tales

**Comment by zztkm** [comment]
Dynmap もコミット見てたら、Paper 向けの 1.20 対応進めてるっぽい
https://dev.bukkit.org/projects/dynmap/files

**Comment by zztkm** [comment]
1.20 起動確認よし！

**Comment by zztkm** [comment]
ローカルでプラグインの自動DLとプラグインの動作検証をやる

**Comment by zztkm** [comment]
20230612 23:00 からサーバーアップデート開始！

**Comment by zztkm** [comment]
最初プラグインダウンロードがなかなか終わらんかったけど、もう一回 `make down & up` かましたら期待通りにダウンロードが進むようになった

**Comment by zztkm** [comment]
検証終わったので完了！
